{{- if .Values.githubExistingSecretName }}
# Existing secret is specified, so no need to create a new one
{{- /* Output a message to indicate using an existing secret */ -}}
{{- printf "Using existing secret: %s" .Values.githubExistingSecretName | quote }}
{{- else }}
# No existing secret specified, create a new secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-github-readonly" (include "common.names.fullname" .) | quote }}
  labels:
    app: {{ include "common.names.fullname" . }}
type: Opaque
data:
  github-token: {{ .Values.githubToken | b64enc | quote }}
{{- end }}
