{{- range $key, $value := .Values.persistence }}
{{- if not $value.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "check-mk.name" $ }}-{{ $key }}
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  accessModes:
    - {{ $value.accessMode }}
  resources:
    requests:
      storage: {{ $value.size }}
---
{{- end }}
{{- end }}
