{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "check-mk.fullname" . }}
  labels:
    app: {{ include "check-mk.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClass }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          {{- range $name, $svc := $.Values.service }}
          {{- if and $svc.enabled (eq (toString $svc.externalPort) "80") }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "check-mk.fullname" $ }}-{{ $name }}
                port:
                  number: {{ $svc.externalPort }}
          {{- end }}
          {{- end }}
    {{- end }}
  {{- if $.Values.ingress.tls }}
  tls:
    {{- range $.Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
